#!/bin/sh
apt-get --yes --force-yes install python3-scipy python3-matplotlib
apt-get --yes --force-yes install python3-django python3-bs4
apt-get --yes --force-yes install python3-reportlab python3-reportlab-accel
apt-get --yes --force-yes install imagemagick gifsicle
cd ~/documents
git clone https://github.com/zunzun/zunzunsite3.git
